### PR TITLE
Fixes for clang

### PR DESCRIPTION
**Pull request by ZeGentzy**
These made it compile with clang... you might want to add them.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I don't see any clang problems with current version.
Which version complains and fails to compile?

**Comment by ZeGentzy** [comment]
On my pc I get "astyle regressions found.", after running "make astyle" I get what I get from the first commit.
Compiling with "make RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 CLANG=1 CCACHE=1 -j4" then gives:
"SOUND -I/usr/include/SDL2 -D_REENTRANT -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -c src/ranged.cpp -o obj/tiles/ranged.o
src/item_action.cpp:246:30: error: lambda capture 'menu_items' is not used [-Werror,-Wunused-lambda-capture]
    const auto sort_menu = [&menu_items]( Iter from, Iter to ) {
                             ^
1 error generated."
And others.

Clang version is "6.0.0 (trunk 310227)", so the warning might not yet be in your version of clang.

**Comment by Coolthulhu** [comment]
Looks like you have updated astyle.
At the moment this repo uses the same astyle as CleverRaven one, which is around 2.03-2.05 (the one in Travis - and thus automatic testing is from ubuntu Trusty).
`make astyle` updates code to current astyle, meaning it will break the code astyled for the version used in repo. So the astyle changes will have to be removed here.

You can override astyle version invoked in `make astyle` by doing `ASTYLE_BINARY="/path/to/binary" make astyle`.

**Comment by Coolthulhu** [comment]
> Another interesting thing is that putting "ASTYLE_BINARY="/home/gentz/Documents/astyle" does NOT stop it from using the system astyle.

I'm not that good with `make`. I think it may work differently depending on which side of `make` is that line on. The following two lines could have different results:
```
ASTYLE_BINARY="/bin/astyle1" make
make ASTYLE_BINARY="/bin/astyle1"
```

I know that it does overwrite environmental variables, so setting ASTYLE_BINARY in a line without `make` will most likely not work.

> Astyle in fact does NOT run on travis.

Looks like I mistook the Jenkins on CleverRaven for Travis. I'll need to add that then.

> The other commits however are required for clang 6.

I'll try to set up the clang 6 to test it then. Travis reports a problem, but it's not on your side (just RNG on Travis side).
Do you mind if I later forward this PR to CleverRaven? It would be less work for me to keep my repo synced that way.
Or you could PR it there and I could merge it from there if you want the "credit".

**Comment by ZeGentzy** [comment]
"Looks like I mistook the Jenkins on CleverRaven for Travis. I'll need to add that then."
My bad, you appear to have misunderstood me, or maybe I misunderstood you. Travis tries to do the test but it fails with the error I quoted above error.

"Do you mind if I later forward this PR to CleverRaven? It would be less work for me to keep my repo synced that way."
I don't mind, feel free.

**Comment by Coolthulhu** [comment]
All right, I tested it. Had to get experimental clang 6 for that. Forwarded to CleverRaven - if it's rejected there, I'll merge it here, otherwise I'll merge it when syncing.

As for the astyle:
I don't really see how would Travis use astyle newer than 2.05 - this is the astyle in Ubuntu LTS repo.
It could be some user-centric Travis thing. For me it shows no problems with current styling.

**Comment by Coolthulhu** [comment]
I forwarded it to cleverraven, where it was merged. Closing here.

**Pull request closed without merging**
