### PR TITLE
Deconstruction furniture now needs prying instead of hammering

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Balance "Deconstruction furniture now needs prying instead of hammering"

#### Purpose of change
Deconstruction needed hammering 2. Which is odd, since I can't remember bashing something with a hammer to dismantle my IKEA furniture... PRYING on the other hand makes a lot of more sense (nail prying).

### CODE REVIEW

**Comment by Saicchi** [comment]
That means the makeshift hammer can no longer be used for deconstruction, and the player will need to use a hammer or makeshift crowbar instead ( just like DDA ).
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/2154cda8a787037962df6649f12004eaf1c0c0bc/data/json/items/tool/workshop.json#L517

**Comment by chaosvolt** [comment]
You can use or statements in tools if you want to preserve the makeshift hammer being usable. Example: `"qualities": [ [ { "id": "PRY", "level": 1 }, { "id": "HAMMER", "level": 2 } ], [ { "id": "SCREW", "level": 1 } ] ],`

Worth noting here is that, if starting from scratch, you still need a source of hammering 2 to make the screwdriver. If screwdrivers were additionally set to only need hammering of 1 then this would be more of a side change with no increase in the number of steps required, whereas right now this technically increases the steps involved by one.

**Comment by Lamandus** [comment]
> You can use or statements in tools if you want to preserve the makeshift hammer being usable. Example: `"qualities": [ [ { "id": "PRY", "level": 1 }, { "id": "HAMMER", "level": 2 } ], [ { "id": "SCREW", "level": 1 } ] ],`
> 
> Worth noting here is that, if starting from scratch, you still need a source of hammering 2 to make the screwdriver. If screwdrivers were additionally set to only need hammering of 1 then this would be more of a side change with no increase in the number of steps required, whereas right now this technically increases the steps involved by one.

I would rather leave the makeshift hammer as is. Since we can do it like this -> stone/Makeshift hammer -> screwdriver AND makeshift crowbar -> deconstruct until proper hammer is found.

**Comment by Coolthulhu** [comment]
Being able to deconstruct things with tools made of wood+rock is a big thing of early game "meta".
Makeshift crowbar getting an important use is OK, but there should be some way to get furniture deconstruction without entering civilization or setting up a forge.

**Comment by Lamandus** [comment]
> Being able to deconstruct things with tools made of wood+rock is a big thing of early game "meta". Makeshift crowbar getting an important use is OK, but there should be some way to get furniture deconstruction without entering civilization or setting up a forge.

bash it down?

**Pull request merged**
