### PR TITLE
Small overhaul of crafting for EMP Grenade (new) and EMP bomb (tweaks),

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Balance "Small overhaul of crafting for EMP Grenade (new) and EMP bomb (tweaks)"

#### Purpose of change
I took a look at the EMP Grenade and the EMP Bomb

The Grenade WAS craftable, which got changed (due to realisms concerns) to non craftable. The scrambler got a Hub01 exclusive. A new object (EMP Bomb) was then introduced. The bomb itself was near to impossible to craft, due to a very rare item (only for that item). So crafting it was out of the league, just looting was an option.
This will somewhat reintroduce and tweak all 3 recipes. Obsolete Fluxcompensator and Microwavethingy because they have no use anymore. It is still hard to craft but not impossible.

#### Describe the solution
See above.

#### Describe alternatives you've considered
Just make the grenade craftable. But I think, it should involve some valuable (fuel cell) stuff, so it isn't easily craftable.

### CODE REVIEW

**Comment by Lamandus** [comment]
> An alternative would be to keep the microwave magnetron idea, ideally also allowing one to craft a makeshift EMP projector with it. The idea the realismic recipe seems to be going for is that of cracking open a magnetic field, which the flux generator thing would've been capable of doing without slapping a magnetron on it, far as I can tell from looking it up.
> 
> Most info I've been able to find about magnetrons used for EMPs meanwhile involves dumping a capacitor into them to make basically a short-range EMP pulse, for the obvious reason that it's a more useful project to dabble in than buying a microwave just to use the magnetron only once. But it does seem that bricking the magnetron while it's running can also generate a similar short-range effect.
> 
> Given how the flux compressor works, if you do retain the magnetron idea then it may be desirable to ditch the plutonium cell and instead add a small amount of explosive. Aside from "doing a recipe influenced by real life but also better than DDA's haphazard implementation" it'd also change the resources needed to make one to something potentially less restrictive.

You also need to check the old old recipe of the "bomb" (back then it was the grenade). So now it is somewhat better.

**Comment by Lamandus** [comment]
I mean, anything can be brought back from obsoletion, but for now, I would go these steps.

**Comment by Coolthulhu** [comment]
This has some possibly-fragile balance involved, I will check the books first then.

**Comment by Coolthulhu** [comment]
As for balance:
* The EMP grenade looks easy to craft, with only plutonium cell being a real limitation
* EMP bomb is more expensive than the grenade, but less specialized. While the idea of a fully electronic bomb sounds cool, the combined EMP+explosion is generally not as useful as sum of the two. Not being able to throw it means it's worse than the grenade, not better.
* What are some use cases of the scrambler?

Think of it as adding the recipes, not just restoring them.
I'd say that the bomb should be easier to craft than the grenade. The grenade should cost something that isn't trivial to get. Not necessarily rare, just something that you might not have tons of. Noble metals?

**Comment by Lamandus** [comment]
> As for balance:
> * The EMP grenade looks easy to craft, with only plutonium cell being a real limitation
> * EMP bomb is more expensive than the grenade, but less specialized. While the idea of a fully electronic bomb sounds cool, the combined EMP+explosion is generally not as useful as sum of the two. Not being able to throw it means it's worse than the grenade, not better.
> * What are some use cases of the scrambler?
> 
> Think of it as adding the recipes, not just restoring them.
> I'd say that the bomb should be easier to craft than the grenade. The grenade should cost something that isn't trivial to get. Not necessarily rare, just something that you might not have tons of. Noble metals?

Some silver or gold?

**Comment by chaosvolt** [comment]
> What are some use cases of the scrambler?

If I recall, the only real use for scramblers is to save prototype cyborgs, because just EMPing them tends to kill them.

**Pull request merged**
